# Form implementation generated from reading ui file 'C:\Users\pc\Documents\programming\personal_projects\invoice_creator\ui\invoice_info_template.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Invoice_info_template(object):
    def setupUi(self, Invoice_info_template):
        Invoice_info_template.setObjectName("Invoice_info_template")
        Invoice_info_template.resize(405, 323)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Invoice_info_template)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Info_layout = QtWidgets.QVBoxLayout()
        self.Info_layout.setObjectName("Info_layout")
        self.header_bar = QtWidgets.QHBoxLayout()
        self.header_bar.setObjectName("header_bar")
        spacerItem = QtWidgets.QSpacerItem(16, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.header_bar.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=Invoice_info_template)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.header_bar.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.header_bar.addItem(spacerItem1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=Invoice_info_template)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.header_bar.addWidget(self.pushButton_3)
        spacerItem2 = QtWidgets.QSpacerItem(16, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.header_bar.addItem(spacerItem2)
        self.Info_layout.addLayout(self.header_bar)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.Info_layout.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(16, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton = QtWidgets.QPushButton(parent=Invoice_info_template)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=Invoice_info_template)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.Info_layout.addLayout(self.horizontalLayout)
        self.line_3 = QtWidgets.QFrame(parent=Invoice_info_template)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.Info_layout.addWidget(self.line_3)
        self.info_table = QtWidgets.QTableView(parent=Invoice_info_template)
        self.info_table.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_table.sizePolicy().hasHeightForWidth())
        self.info_table.setSizePolicy(sizePolicy)
        self.info_table.setObjectName("info_table")
        self.Info_layout.addWidget(self.info_table)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(16, 16, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.save_button = QtWidgets.QPushButton(parent=Invoice_info_template)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_2.addWidget(self.save_button)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.Info_layout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.Info_layout)

        self.retranslateUi(Invoice_info_template)
        self.save_button.clicked.connect(Invoice_info_template.save) # type: ignore
        self.pushButton_3.clicked.connect(Invoice_info_template.load) # type: ignore
        self.pushButton_2.clicked.connect(Invoice_info_template.add_row) # type: ignore
        self.pushButton.clicked.connect(Invoice_info_template.delete_selected) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Invoice_info_template)

    def retranslateUi(self, Invoice_info_template):
        _translate = QtCore.QCoreApplication.translate
        Invoice_info_template.setWindowTitle(_translate("Invoice_info_template", "Form"))
        self.label.setText(_translate("Invoice_info_template", "Invoice info"))
        self.pushButton_3.setText(_translate("Invoice_info_template", "..."))
        self.pushButton.setWhatsThis(_translate("Invoice_info_template", "Delete selection"))
        self.pushButton.setText(_translate("Invoice_info_template", "-"))
        self.pushButton_2.setWhatsThis(_translate("Invoice_info_template", "Add row beneath selection"))
        self.pushButton_2.setText(_translate("Invoice_info_template", "+"))
        self.save_button.setText(_translate("Invoice_info_template", "save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Invoice_info_template = QtWidgets.QWidget()
    ui = Ui_Invoice_info_template()
    ui.setupUi(Invoice_info_template)
    Invoice_info_template.show()
    sys.exit(app.exec())
