# Form implementation generated from reading ui file 'C:\Users\pc\Documents\programming\personal_projects\invoice_creator\ui\tax_row_template.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tax_row(object):
    def setupUi(self, tax_row):
        tax_row.setObjectName("tax_row")
        tax_row.resize(540, 67)
        self.horizontalLayout = QtWidgets.QHBoxLayout(tax_row)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tax_name = QtWidgets.QLineEdit(parent=tax_row)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tax_name.sizePolicy().hasHeightForWidth())
        self.tax_name.setSizePolicy(sizePolicy)
        self.tax_name.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhLatinOnly)
        self.tax_name.setText("")
        self.tax_name.setFrame(True)
        self.tax_name.setClearButtonEnabled(False)
        self.tax_name.setObjectName("tax_name")
        self.horizontalLayout.addWidget(self.tax_name)
        self.label = QtWidgets.QLabel(parent=tax_row)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.tax_percentage = QtWidgets.QDoubleSpinBox(parent=tax_row)
        self.tax_percentage.setMaximum(100.0)
        self.tax_percentage.setObjectName("tax_percentage")
        self.horizontalLayout.addWidget(self.tax_percentage)
        self.label_2 = QtWidgets.QLabel(parent=tax_row)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.line = QtWidgets.QFrame(parent=tax_row)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.tax_calc = QtWidgets.QLineEdit(parent=tax_row)
        self.tax_calc.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tax_calc.sizePolicy().hasHeightForWidth())
        self.tax_calc.setSizePolicy(sizePolicy)
        self.tax_calc.setText("")
        self.tax_calc.setFrame(True)
        self.tax_calc.setReadOnly(True)
        self.tax_calc.setObjectName("tax_calc")
        self.horizontalLayout.addWidget(self.tax_calc)
        self.dzd = QtWidgets.QLabel(parent=tax_row)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dzd.setFont(font)
        self.dzd.setObjectName("dzd")
        self.horizontalLayout.addWidget(self.dzd)
        self.pushButton = QtWidgets.QPushButton(parent=tax_row)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(tax_row)
        self.pushButton.clicked.connect(tax_row.remove) # type: ignore
        self.tax_percentage.valueChanged['double'].connect(tax_row.rate_changed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(tax_row)

    def retranslateUi(self, tax_row):
        _translate = QtCore.QCoreApplication.translate
        tax_row.setWindowTitle(_translate("tax_row", "Form"))
        self.label.setText(_translate("tax_row", ":"))
        self.label_2.setText(_translate("tax_row", "%"))
        self.tax_calc.setToolTip(_translate("tax_row", "Total before tax"))
        self.dzd.setText(_translate("tax_row", "DZD"))
        self.pushButton.setText(_translate("tax_row", "Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tax_row = QtWidgets.QWidget()
    ui = Ui_tax_row()
    ui.setupUi(tax_row)
    tax_row.show()
    sys.exit(app.exec())
